name: Build and Push Docker Image

on:
  push:
    tags: [ 'v*', 'v*.*', 'v*.*.*' ]
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 'Custom tag for the image'
        required: false
        type: string
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check secrets exist
      run: |
        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          echo "ERROR: DOCKERHUB_USERNAME secret is not set!"
          exit 1
        fi
        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "ERROR: DOCKERHUB_TOKEN secret is not set!"
          exit 1
        fi
        echo "Secrets are configured correctly"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: dk6v/healthcheck
        tags: |
          type=raw,priority=30,value=latest,enable=true
          type=semver,priority=20,pattern={{version}}
          type=raw,priority=10,value=${{ github.event.inputs.custom_tag }},enable=${{ github.event_name == 'workflow_dispatch' }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
